---
- name: Despliegue con Ansible
  hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Instalando prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Instalando Services
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Creando documento root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Configuramos  Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Habilitamos el nuevo sitio
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Deshabilitamos el sitio deafult de Apache
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: Agregamos las contraseñas al root
      mysql_user:
        login_user: root
        login_password: " "
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Removemos los usuarios anonimos
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Dropeamos las bases de prueba
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
        
    - name: Creamos la base de la app
      mysql_db: name=crud state=present login_user=root login_password=" "
      
    - name: Agregamos el archivo script
      copy: src=files/db.sql dest=/tmp/db.sql
      
    - name: Agregamos las tablas de la base
      mysql_db: name=crud state=import target=/tmp/db.sql login_user=root login_password=" "  
  
    - name: "Habilitamos la comunicacion por los puertos {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: Clonamos el repositorio desde GitHub
      git:
        repo: 'https://github.com/RamsesCastro24/crud.git'
        dest: /var/www/{{ http_host }}

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted